AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'packages/**/*'
    - 'vendor/**/*'
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Exclude:
    - '*.gemspec'
Metrics/AbcSize:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
